name: Build ISO

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install depends
      run: |
        sudo apt-get -y install flex bison libssl-dev libelf-dev libncurses-dev
    - name: Build Linux 
      run: |
        git clone --depth=1 https://github.com/torvalds/linux.git
        cd linux
        make defconfig
        make -j$(nproc)

    - name: Build Busybox
      run: |
        git clone --depth=1 https://github.com/busybox/busybox.git
        cd busybox
        make defconfig
        make -j$(nproc)

    - name: Build GRUB
      run: |
        git clone --depth=1 https://github.com/grub/grub.git
        cd grub
        ./autogen.sh
        ./configure
        make -j$(nproc) 

    - name: Create ISO
      run: | 
        mkdir -p iso/boot/grub
        cp linux/arch/x86/boot/bzImage iso/boot
        cp busybox/busybox iso/bin
        cp grub/grubx64.efi iso/boot/grub
        genisoimage -output iso.iso -volid MYLINUX -joliet -rock iso/
