name: Build root
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install mmdebstrap and xorriso
        run: sudo apt-get update && sudo apt-get install -y mmdebstrap xorriso
      - name: Create minimal Ubuntu ISO
        run: |
          mkdir rootfs
          cd rootfs
          sudo mmdebstrap --variant=apt \
          --dpkgopt='path-exclude=/usr/share/man/*' \
          --dpkgopt='path-exclude=/usr/share/doc/*' \
          --dpkgopt='path-exclude=/usr/share/locale/*' \
          --dpkgopt='path-include=/usr/share/doc/*/copyright' \
          --include=tree,jq \
          jammy testing http://jp.archive.ubuntu.com/ubuntu
          ls -l
